<table>
	<tr>
		<td>您好！这是一封来自楚誉协同办公系统的通知邮件！</td>
	</tr>
	<tr>
		<td>你的日期为【${time}】日清日结还未提交！请登陆系统提交您的日志！</td>
	</tr>
	<tr>
		<td>http://www.chuyutech.com:8888/oa</td>
	</tr>
	<tr>
		<td>如未及时提交日志，可能会被扣除相应的工资！</td>
	</tr>
	<tr>
		<td>感谢您的配合!</td>
	</tr>
	<tr>
		<td>By.楚誉协同办公系统</td>
	</tr>
</table>